    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'

        - uses: actions/checkout@v2
        - uses: education/autograding@v1
